name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install TinyTeX and required TeX packages
      run: |
        sh tools/install-bin-unix.sh
        export PATH=/home/runner/.TinyTeX/bin/x86_64-linux/:$PATH
        echo $PATH
        tlmgr install comment polyglossia xkeyval metalogo fonts-churchslavonic libertine luacolor lettrine hypdoc hyphen-russian hyphen-churchslavonic

    - name: Run TeX tests
      run: make test
