name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install TinyTeX
      run: |
        sh tools/install-bin-unix.sh
        echo "PATH=~/.TinyTeX/bin:$PATH" >> $GITHUB_ENV
        echo $PATH

    - name: Install required packages
      run: |
        echo $PATH
        /home/runner/.TinyTeX/bin/tlmgr install comment polyglossia xkeyval metalogo fonts-churchslavonic libertine luacolor lettrine hypdoc hyphen-russian hyphen-churchslavonic

    - name: Run TeX tests
      run: make tests
